### ISSUE TITLE
LCA with Mixed Features

### ISSUE THREAD

**Issue by sarasilvacunha** [Labo-Lacourse/stepmix#13]
Hi!!! 
I'm having a problem with the "measurement" parameter in a database with 3 categorical and 25 continuous variables. I followed the example you share and in my Python it doesn't accept the variable "mixed_descriptor". The error that appears is the following:

" ValueError: emission value mixed_descriptor not recognized. Choose from dict_keys(['gaussian', 'gaussian_unit', .......etc.......]) "

Could you help me please?

**Comment by sachaMorin** [comment]
Hi! Could it be that you are passing the string "mixed_descriptor" instead of the variable mixed_descriptor? As discussed in the [tutorial](https://colab.research.google.com/drive/1KAxcvxjL_vB2lAG9e47we7hrf_2fR1eK?usp=sharing#scrollTo=6A3io6d7Yy-v), you need to pass the variable returned by get_mixed_descriptor (in fact, a Python dict) to the measurement parameter.

**Comment by sachaMorin** [comment]
Otherwise, I would be happy to help if you provide the exact code leading to the error. Cheers!

**Comment by sarasilvacunha** [comment]
Hi!!! I restarted the kernel and that solved my problem :D
Thank you very much for your attentiveness. Thanks also for sharing your content!!
